# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html

imports:
    - { resource: "@UserBundle/Resources/config/security.yml"}
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/temoin, role:  ROLE_USER}