<?php

namespace HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnalysesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalysesRepository extends EntityRepository
{
}
