<?php

namespace HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CartesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartesRepository extends EntityRepository
{
}
