<?php

namespace HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarteValeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteValeurRepository extends EntityRepository
{
	public function CarteEnCours($carte)
	{

	return $nom = $this->createQueryBuilder('c')
    ->select('DISTINCT c.nom')
    ->where('c.carte = :carte')
    ->andWhere('c.SuppressionVisuel = true')
    ->setParameter('carte', $carte)
    ->getQuery()
    ->getResult();
	}


    public function nomExiste($carte , $nom)
    {
        return $nom = $this->createQueryBuilder('c')
        ->select('DISTINCT c.nom')
        ->where('c.carte = :carte')
        ->andWhere('c.SuppressionVisuel = true')
        ->andWhere('c.nom = :nom')
        ->setParameter('carte', $carte)
        ->setParameter('nom', $nom)
        ->getQuery()
        ->getResult();
    }


}



