<?php

namespace HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TemoinsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemoinsRepository extends EntityRepository
{

		


    public function TemoinsEnCours($now)
	{
    return $this->createQueryBuilder('t')
        ->where('t.datePeremption > :now')
        ->setParameter('now', $now)
        ->getQuery()
        ->getResult();
	}
}
